# Generated by Django 4.2 on 2024-12-05 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='users.candidate'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_applications', to='jobs.jobopening'),
        ),
        migrations.AddConstraint(
            model_name='jobopening',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'O')), fields=('position', 'city'), name='unique_job_opening_per_position_city'),
        ),
    ]
