# Generated by Django 4.2 on 2024-12-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('jobs', '0003_alter_jobopening_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='optional_skills',
            field=models.ManyToManyField(related_name='optional_for_positions', to='skills.skill'),
        ),
    ]
