# Generated by Django 4.2 on 2024-12-06 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('expected_points', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRoundRatingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MySheet', max_length=200)),
                ('comment', models.TextField(blank=True, default='')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewround')),
            ],
        ),
        migrations.CreateModel(
            name='RatingSheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_max', models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(100)])),
                ('aspects', models.ManyToManyField(blank=True, related_name='aspects', to='ratings.aspecttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RatingAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('expected_points', models.PositiveIntegerField(default=0)),
                ('round_rating_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.interviewroundratingsheet')),
            ],
        ),
    ]
