services:
 db:
   image: postgres:17
   container_name: project_imt_postgres_db
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
     - logs:/code/logs
   env_file:
     - .env
 
 django-web:
   build: .
   container_name: project_imt_container
   working_dir: /code # This lets you bash into the project directory.
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
     SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     ALLOWED_HOSTS: ${ALLOWED_HOSTS}
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${POSTGRES_USER}
     DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
     DATABASE_HOST: ${POSTGRES_HOST}
     POSTGRES_PORT: ${POSTGRES_PORT}
     DJANGO_ENV: ${DJANGO_ENV}
   env_file:
     - .env
volumes:
   postgres_data:
   logs: