# Generated by Django 4.2 on 2024-12-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('T', 'Telephonic'), ('V', 'Video'), ('W', 'Written'), ('F', 'Face-to-Face')], default='T', max_length=1)),
                ('scheduled_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('A', 'Advanced'), ('F', 'Fail'), ('N', 'No Decision')], default='N', max_length=1)),
            ],
        ),
    ]
