# Generated by Django 4.2 on 2024-12-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='duration_in_mins',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
